# Generated by Django 5.0.6 on 2024-06-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='debut',
            field=models.CharField(max_length=50),
        ),
    ]
