# Generated by Django 5.0.6 on 2024-06-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0003_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
